# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rstrauss_BD <- function(dim, beta, gamma, R, win, iter, dbg) {
    .Call('rstrauss_rstrauss_BD', PACKAGE = 'rstrauss', dim, beta, gamma, R, win, iter, dbg)
}

rstrauss_DCFTP <- function(dim, beta, gamma, R, win, T0, dbg, maxtry) {
    .Call('rstrauss_rstrauss_DCFTP', PACKAGE = 'rstrauss', dim, beta, gamma, R, win, T0, dbg, maxtry)
}

rstrauss_MH <- function(dim, n, gamma, R, win, iter, dbg) {
    .Call('rstrauss_rstrauss_MH', PACKAGE = 'rstrauss', dim, n, gamma, R, win, iter, dbg)
}

