# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rstrauss_BD <- function(beta, gamma, R, win, toroidal, iter, dbg, blocking) {
    .Call('rstrauss_rstrauss_BD', PACKAGE = 'rstrauss', beta, gamma, R, win, toroidal, iter, dbg, blocking)
}

rstrauss_DCFTP <- function(beta, gamma, R, win, toroidal, T0, dbg, maxtry, blocking) {
    .Call('rstrauss_rstrauss_DCFTP', PACKAGE = 'rstrauss', beta, gamma, R, win, toroidal, T0, dbg, maxtry, blocking)
}

rstrauss_MH <- function(n, gamma, R, win, toroidal, iter, dbg, blocking, start) {
    .Call('rstrauss_rstrauss_MH', PACKAGE = 'rstrauss', n, gamma, R, win, toroidal, iter, dbg, blocking, start)
}

